version: 0.2

phases:
  pre_build:
    commands:
      - sudo apt update
      - sudo apt install python3
      - sudo apt install python3 -y
      - sudo apt install python3-pip -y
      - sudo pip3 install detect-secrets
  post_build:
    commands:
      - echo "installed detect-secrets"
      - detect-secrets --version
