version: 0.2

phases:
  pre_build:
    commands:
      - sudo apt update 
      - sudo apt install python3 -y   #Installing Python
      - sudo apt install python3-pip -y #Installing pip dependency
      - sudo pip3 install detect-secrets #Installing detect-secrets using pip
  post_build:
    commands:
      - echo "installed detect-secrets"
      - detect-secrets --version
