version: 0.2

phases:
  install:
    #runtime-versions:
      # name: version
      # name: version
    commands:
      - sudo apt update 
      - sudo apt install python3 -y   #Installing Python
      - sudo apt install python3-pip -y #Installing pip dependency
      - sudo pip3 install detect-secrets #Installing detect-secrets using pip
    finally:
      - echo This is secret-scan stage using detect-secrets tool
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo "installed detect-secrets"
      - detect-secrets --version
  build:
    commands:
      #- git clone --branch master https://Mukeshit91@bitbucket.org/Mukeshit91/docker-vulnerable-dvwa.git
      - echo "Perform build steps here"
      - sudo rm gitsecret_report.json || true
      - detect-secrets scan --all-files > .secrets.baseline
      - detect-secrets -C . scan > gitsecret_report.json
      - cat gitsecret_report.json || true
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
  
