---
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt update
      - apt install python3 -y
      - apt install python3-pip -y
      - pip3 install detect-secrets
  pre_build:
    commands:
      - echo "Installed detect-secrets"
      - detect-secrets --version
  build:
    commands:
      - echo "Perform build steps here"
      - rm gitsecret_report.json || true
      - detect-secrets scan --all-files > .secrets.baseline
      - detect-secrets -C . scan > gitsecret_report.json
      - cat gitsecret_report.json || true
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files: gitsecret_report.json
